# Generated by Django 3.2.6 on 2021-09-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(choices=[('Peon', 'Peon'), ('Lab Assistant', 'Lab Assistant'), ('Sweeper', 'Sweeper'), ('Librarian', 'Librarian'), ('Computer Operator', 'Computer Operator'), ('Clerk', 'Clerk'), ('Security Guard', 'Security Guard')], max_length=32),
        ),
    ]
