# Generated by Django 3.2.6 on 2021-09-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BranchApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('salary', models.FloatField()),
                ('branch', models.ManyToManyField(to='BranchApp.Branch')),
            ],
        ),
    ]
