# Generated by Django 3.2.6 on 2021-08-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BranchApp', '0001_initial'),
        ('ProfApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof',
            name='dept',
        ),
        migrations.AddField(
            model_name='prof',
            name='branch',
            field=models.ManyToManyField(to='BranchApp.Branch'),
        ),
    ]
