# Generated by Django 3.2.6 on 2021-09-13 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DeptApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('intake', models.IntegerField()),
                ('college_fees', models.FloatField(default=0)),
                ('exam_fees', models.FloatField(default=0)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeptApp.dept')),
            ],
        ),
    ]
