# Generated by Django 3.2.6 on 2021-09-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BranchApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='college_fees',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='exam_fees',
            field=models.FloatField(default=0),
        ),
    ]
