# Generated by Django 3.2.6 on 2021-08-29 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BranchApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BranchApp.branch')),
            ],
        ),
    ]
