# Generated by Django 3.2.6 on 2021-08-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='dept',
            new_name='branch',
        ),
    ]
