# Generated by Django 3.2.6 on 2021-09-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0002_rename_dept_student_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college_fees',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='exam_fees',
            field=models.FloatField(default=0),
        ),
    ]
